name: flutter_event
description: 'Event'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # A
  app_settings: ^7.0.0

  # C
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  cloudinary_public: ^0.23.1

  # D
  dio: ^5.4.1
  dartz: ^0.10.1

  # E
  equatable: ^2.0.5

  # F
  flutter_secure_storage: ^10.0.0
  flutter_spinkit: ^5.2.1
  flutter_local_notifications: ^20.0.0
  flutter_quill_delta_from_html: ^1.5.2
  flutter_quill: ^11.4.1
  file_picker: ^10.1.9
  flutter_html: ^3.0.0
  flutter_dotenv: ^6.0.0

  # G
  get_it: ^9.2.0

  # P
  provider: ^6.1.2
  permission_handler: ^12.0.0+1

  # S
  shared_preferences: ^2.2.2

  # T
  table_calendar: ^3.1.3

  # U
  uuid: ^4.5.1

  # V
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
